<?php
    include_once("./src/env.include.php");
?>
<?php
    include_once("./src/head.inc.php")
?>
<body>
<?php
include_once('./src/header.inc.php');
?>
    <?php
    include_once("./src/main.inc.php");
?>
</body>
<?php 
include_once('./src/footer.inc.php');
?>
</html>
    